### ISSUE TITLE
X-1 and Bonanza cockpits have negative cost

### ISSUE THREAD

**Issue by nepphhh** [KSP-RO/RealismOverhaul#2085] opened 2019-06-17 20:54 UTC
As mentioned by various players in the RSSRO discord.

**Comment by marb1** [comment] 2019-06-18 00:57
The negative costs for these cockpits is associated with ROKerbalism and not RO.

The problem is that KSP assumes tank costs are "wet". If the cockpit actually starts with 0 of that resource, the costs of filling the tank are deducted from the part cost. This is particularly noticeable for the "shielding" resource from Kerbalism which is 50/unit. When you fill up shielding on these cockpits in the PAW, the "correct" cost is recovered.

I tried to see how tank costs for crewed compartments are implemented in ROKerbalism, but couldn't figure it out. Maybe @Standecco could weigh in here.

**Comment by Standecco** [comment] 2019-06-18 06:51
@marb1 that is weird. Since I can't check rn, what is the behavior with other parts? Does the cost get deducted or added?

**Comment by TheRealWiwaxia** [comment] 2019-06-18 07:10
> 
> 
> @marb1 that is weird. Since I can't check rn, what is the behavior with other parts? Does the cost get deducted or added?

I can replicate this bug too. The Junkers Ju 87 and the He 111 cockpits also seem to have this deduction problem without shielding, a few non-ro parts like the Mk1 capsule also have the shielding problem.

**Comment by marb1** [comment] 2019-06-18 10:21
@Standecco 
As noted by @TheRealWiwaxia the cost deduction (50 * units of shielding) appears to occur for all crewed compartments. There's a really old forum thread that appears to be about this, https://forum.kerbalspaceprogram.com/index.php?/topic/95588-help-please-empty-resource-containers-cause-negative-cost-in-vab/

Could be this is happening for every resource that starts empty but only noticeable for shielding because of how expensive it is compared to poop and wastewater.

**Comment by nepphhh** [comment] 2019-06-26 17:56
Using Dang It! also deducts the cost of the SpareParts resource.

**Comment by DRVeyl** [comment] 2020-07-12 22:22
Going to close this issue.  RO generally does not do costs, that's in the realm of RP-1 [or any career mod where cost has meaning], and this sounds like it has been addressed by ROKerbalism.  This is something we might need to keep in mind for eg Life Support/TACLS configs.  Do resources stored in ModuleFuelTanks suffer the same issue as RESOURCE nodes directly attached to a part?

**Closed by DRVeyl** 2020-07-12 22:22 UTC
