### ISSUE TITLE
TF config errors

### ISSUE THREAD

**Issue by ec429** [KSP-RO/RealismOverhaul#1968] opened 2019-01-01 15:14 UTC
So I don't forget, here's errors I've spotted in TF configs while lovingly ripping them off for SPEngine.

The big one: techTransfer lists need to be in reverse order — the _first_ engine in the list is the newest.  See https://github.com/KSP-RO/TestFlight/wiki/Module-Reference:-TestFlightCore

Also, we should probably set techTransferGenerationPenalty to something bigger (at least 0.25); at the moment an engine five generations away can still contribute 80% of its data, which is just silly.  Especially as it can _also_ contribute data indirectly (transfer A->B and then B->C, but also get the direct A->C transfer with the tiny penalty).  This would need plumbing through in TestFlight_Generic_Engines.cfg.

Agena has a TF config for Model8096-39A, but the engine config is called Model8096A.  I don't know which of those is better, but they don't match so the TF config doesn't apply to anything.  Same goes for Model8096-39L.

**Comment by Bornholio** [comment] 2019-01-04 02:09
don't want to penalize rigorous testing of generations, but yeah it comes too fast if you have an engine line stacked

**Comment by Capkirk123** [comment] 2020-07-14 23:40
The latter part of this has been resolved, (almost) all engines now have a correctly configured TF config. The latter is probably a question for @jwvanderbeck and the upcoming changes to TF v2

**Comment by jwvanderbeck** [comment] 2020-07-15 01:28
If you mean the tech transfers.. the algorithm has not changed, but the bug that would allow transfers to exceed the maximum transfer du has been fixed.  So tech transfer now caps as it was intended to.

**Comment by DRVeyl** [comment] 2020-07-15 02:23
Do we still need to address "Also, we should probably set techTransferGenerationPenalty to something bigger (at least 0.25)" specifically?

**Comment by DRVeyl** [comment] 2021-03-31 23:59
If there are no comments to "Also, we should probably set techTransferGenerationPenalty to something bigger (at least 0.25)" specifically?" then I will assume the answer is "no" and close this issue this weekend.

**Closed** 2021-04-03 17:08 UTC
