### ISSUE TITLE
fuels being used between stages

### ISSUE THREAD

**Issue by Tomfooleryyt** [KSP-RO/RealismOverhaul#2577] opened 2022-01-13 19:27 UTC
![EavKGzD](https://user-images.githubusercontent.com/97699487/149396007-6e86320d-1089-4b3c-9338-1b4b0e277144.jpg)
Fuels are being used by earlier stages. in the picture the helium in the second stage is being used by the engine on the first stage. as well as the nitrogen is being used by the rcs on the first stage
[ModuleManager.zip](https://github.com/KSP-RO/RealismOverhaul/files/7865468/ModuleManager.zip)

**Comment by NathanKell** [comment] 2022-01-16 05:39
The solution here is to specify the resource flow mode in the PROPELLANT node in the engine CONFIG, to override the base resource behavior. So engines that use: nitrogen, helium, water, and (anything else that doesn't have STACK_PRIORITY_SEARCH) need to have their flow mode overridden to STACK_PRIORITY_SEARCH.

**Comment by DRVeyl** [comment] 2022-04-13 18:25
Which resource types are those?
Base RO [so just RF -> CRP] Nitrogen and Helium are already STACK_PRIORITY_SEARCH.  I think just water is not.  I guess Kerbalism will change Nitrogen and Helium to use in LS?  (Tho since Kerbalism resource handling is vessel-wide, why does that happen?)

**Comment by gonsy00** [comment] 2022-05-22 19:17
Hi. I'm having the same issues here with the resource fuelfow.

First, I have very basic knowledge of code. And i dont want to cause any troubles. But hope you can help me.

I did try any kind of things. I did fresh reinstall ksp, fresh reinstall RP1 with ckan, start new games, use any kind of decouplers, interstages, changed the decouplers option of cross-feed (in case it was showing wrong), etc etc etc 
Every time I try to create a rocket, I have to be very careful about the fuel chosen for every stage, or block the resource of the superior stages,  on the "part window", inside the VAB or the actual flight. Also, remember to unlock it before to ignite an engine. And if I forget for any means, it fails after a few hours spent on the mission.

I had being trying to look for the resourceflow mode inside the engine configuration, for manual switching it, but I only could find a few of them inside (GAMEDATA\RealismOverhaul\RO_resources.cfg), and they are already STACK_PRIORITY_SEARCH.

I won't like to cause trouble,  but it will be cool to know where are them "flowmode" engine configurations, as I can't find them. I looked into Realfuels, Realism overhaul, RP0, Kerbalism....
Also, I wouldnt mind to check whatever you need, if that help you improve your mods.

Of course, thanks a lot to everybody who is contributing to RO related mods, as thats one of the best thinks that make me relax after a long day on the constuction job...

Regards

**Comment by Capkirk123** [comment] 2022-11-23 02:18
This should have been fixed? I cannot reproduce, at least.

**Comment by Capkirk123** [comment] 2023-02-16 03:24
To the best of my knowledge all engines that use fuels with unusual flowmode settings have been corrected (although the flowmode still appears as the default flowmode in UI, they do function correctly). Closing for now.

**Closed by Capkirk123** 2023-02-16 03:24 UTC
