### ISSUE TITLE
Heatshield model on Apollo CM needs adjusting

### ISSUE THREAD

**Issue by JandCandO** [KSP-RO/RealismOverhaul#585] opened 2015-10-11 23:46 UTC
It looks like the model just needs to be shifted up a little.

http://i.imgur.com/GrunMFE.png

**Comment by xv323** [comment] 2015-10-12 09:18
I'm not actually sure why realism overhaul has combined the FASA Apollo CM and Apollo heat shield at all. I'm the person who uploaded the image linked to here. In standard FASA the heat shield and command module are two separate parts, which is far more versatile in terms of using either part for different functions. The fact that realism overhaul has combined the two means that, when I edit the command module config file to remove the heat shield, I then can't attach the heat shield as a separate part properly - the attachment nodes are all screwy.

I don't see where the benefit is in trying to combine these two parts really. I would lobby for them to be separated and treated as separate parts again much as FASA originally does.

**Comment by RedAV8R** [comment] 2015-10-12 10:04
Because the heat shield is a part of the Command Module. This is Realism Overhaul...kinda emphasis on the Realism part. Now obviously the two seem to have some issues. That will be corrected. What can also happen is the heat shield remain it's own separate part to be used elsewhere. But the Apollo + Heatshield will remain.

**Comment by xv323** [comment] 2015-10-12 10:07
I'm not sure how having the two as separate parts in any way detracts from the realism. I mean, for starters, the command module hull and the lower ablative shield were built as separate parts and mated together in the actual Apollo program. But in any case, if you want your command module with its realistic heat shield... just attach it to the base in the VAB? I'm really not sure what the problem there is.

FASA was put together such that the heat shield and command module were separate parts. I'm a bit uncomfortable with realism overhaul deciding of its own volition to start messing around with that. Particularly as FASA is suggested as a 'compatible mod' but not listed as a dependency, you would think RO wouldn't start messing around with the basic way in which FASA works.

**Comment by RedAV8R** [comment] 2015-10-12 10:12
Parts have been 'glued' together throughout RO. Even FASA. Just off the top of my head we've permanently attached the RCS pods to the lunar module. Those were parts that were mated during assembly. So by your logic we need to remove those too right???

**Comment by xv323** [comment] 2015-10-12 10:25
Well yes, to be honest. I mean, that particular instance wasn't bothering me because I'm not trying to use the lunar module in the particular mission I'm attempting to do, but I think it should be left up to the player how to use the parts that are contained in a mod that's completely separate from, and independently developed from, RO - surely? If I wanted to use the LM ascent stage in a vehicle with a different configuration to the real-world lunar module, with a  different centre of gravity and therefore requiring different RCS placement, I don't see why RO should preclude that when the relevant bits of the spacecraft were already made into separate parts by an entirely different mod. Conversely, if I want to built the realistic lunar module - I can still do that.

I downloaded FASA because I wanted to be able to use FASA as it was put together by the guy who developed it, and part of that includes having access to all the parts that he decided to include in his mod.

FASA as you are no doubt aware contains a lot of fictional rockets, stuff that was never built, and people have used it to create fictional mission modes using lots of assorted Apollo parts. There's a good example at the following link: https://www.youtube.com/watch?v=BmOngtvYrzc

I don't see why realism overhaul should preclude doing that. Surely the 'realism' is contained in how this newly constructed hypothetical craft behaves, how it flies, how its systems function and so on?

I'm well aware that a counter-argument to this is that if I don't like what Realism Overhaul does I should just not use it. I want to make it plain - the vast majority of what RO contains is very exciting stuff to me, stuff I really want to use. Correctly-scaled parts, realistic engine functionality and so on. I just don't see that it makes any sense to start combining parts from other mods and changing and limiting the ways in which those parts can be utilised - limiting what parts I can use from other mods, how I can use them, and so on.

**Comment by RedAV8R** [comment] 2015-10-12 10:56
Well. I'm sorry you feel that way. What you see has been done since the beginning of RO, and I don't see it changing. You are free of course to not use RO, modify RO to suit yourself, even fork and release it yourself.

**Comment by stratochief66** [comment] 2015-10-12 15:46
@xv323 

@NathanKell asked me about this last night. The reason I combined the two parts was out of necessity when KSP went to 1.0+ and the heating model changed. 

I tried for many hours to get the capsule to -not- explode due to overheating in re-entry, but could not get it to work. The main reason I believe is that the Apollo capsule tilts substantially during re-entry to generate lift, which exposed the capsule part to re-entry heating and blew it up.

I will see what I can do about getting the capsule and heatshield back into harmony, then possibly at also having the capsule and heatshield available as seperate parts again for attachment purposes. Just don't be surprised if the capsule explodes due to re-entry heating without being welded to the heatshield. :P

@NathanKell suggested that KSP 1.0.5 might make re-entry heating a little more gentle to us modders, but that remains to be seen.

**Comment by stratochief66** [comment] 2015-10-12 17:20
@xv323 I checked out the Apollo capsule with a fresh CKAN install of FASA, RO, and essential related mods. I did not see the spacing issue.

Could you please provide more information regarding the conditions where you saw the issue? ie. Did you install using CKAN, or from the forum, or from Github? etc.

Much appreciated ;)

**Comment by xv323** [comment] 2015-10-16 21:59
@stratochief66 - Hi, and apologies that I did not initially see your comments on here.

I hope, incidentally, that I did not come across too harshly in my earlier remarks here - I appreciate the colossal effort people like yourself put in to produce these superb mods and I may not have got that across well enough. Any comments I made about issues with Realism Overhaul should be taken with that in mind - I appreciate that complaining about these things very strongly is much like being given a free three-course meal and complaining that it doesn't have enough salt!

In any case, the issues I was having sadly meant RO wasn't going to work with what I was trying to do, so I've subsequently switched to using ROMini.cfg. I did, however, make a detailed post on the Kerbal Space Program subreddit describing the issue - link is here: https://www.reddit.com/r/KerbalAcademy/comments/3odc1g/very_specific_problem_with_realism_overhaul_can/

Missing info in there is that I did not perform the install of RO using CKAN - I downloaded the zip from Github and then, because Mac OSX seems to unzip filed automatically, I manually moved the files into their relevant locations, following the instructions given in the read me. It was the same process for all the dependent mods that were listed on the forum as being required for RO - I went through this list and ensured I had them all and the installs for all of them were also done by manually moving files.

**Comment by stratochief66** [comment] 2015-10-17 05:46
Thanks for getting back to us @xv323!

No worry mate, I appreciate feedback about play behaviour and bugs like this as much as you appreciate us bringing the mods to you. RO users put tons more time into playing and finding bugs and issues than I ever could when I'm working out issues.

I could have spent hours chasing my tail, trying to reproduce the bug using various combos of various RO related mods (CKAN RO & Github FASA, etc., etc.), so your info about specifically how you acquired the mods is a big help. 

I will take a look again at this tomorrow. Did you acquire your copy of FASA through the forum or, Github? It would help if you posted the link to where you got it, if possible.

I use this mod:
http://forum.kerbalspaceprogram.com/threads/128467-1-0-4-NodeHelper-tool-used-to-edit-node-positions

To help me place and adjust nodes which happens all the time when tweaking and configuring mods. It should make it relatively easy for me to re-add a node to a non-heatshielded Apollo capsule.

I would definitely like to preserve as much of the original function of FASA as possible in the RO config, but in this case I couldn't find a way to keep the capsule from exploding due to re-entry heating with the shield as a separate part. I will look at keeping them separate entirely when 1.0.5 comes out. I have welded a few parts to make crazy complex rockets like the Saturn V easier to assemble, but I see your points. A while after I started some basic welding, I came to the idea of creating *.craft files to that users can have or see the craft fully assembled in their own VAB, which should hopefully be making complex craft waaay easier for people to fly and recreate themselves.

**Comment by RedAV8R** [comment] 2015-10-17 11:00
I'd like to add, I just did my own test and the heat shield is attached in the correct position for me as well using the latest download of FASA and the latest release of RO.

@xv323 . Could we please get a log. That would be the best way to see what is all modifying your stuff. In addition you can look in the ModuleManager.ConfigCache file to see what the end result is and compare that to the RO config. Prove to yourself that if they don't match something else is changing it.

I would also strongly advise, making a fresh install of KSP with basic dependencies of RO only plus FASA and see what you get.

**Comment by stratochief66** [comment] 2015-10-17 18:49
@xv323 I tried again with KSP RO from Github and fresh FASA as well, I'm still not seeing the spacing issue in my installs.

Your logs would be handy (KSP_Data/output_log.txt   and    (GameData/ModuleManager.ConfigCache)

in your screenshot, you also seem to have many other mods, some of which I don't recognize. Please try with a clean KSP install and just RO and FASA if you can.

**Comment by xv323** [comment] 2015-10-17 22:00
Hi guys.

I'll try to get to this tomorrow. As I say, my install of KSP no longer contains the full-fat Realism Overhaul and its dependencies - instead I'm using RO-Mini at the present time - so it'll take me a bit of time to clear everything out and reproduce the circumstances in which this bug was occurring for me. I'll also try an install with just RO and FASA, as you suggest. Do you suggest that, along with RO, I include in this new install all the mods that are listed as required for RO to work properly, or not? Stuff like RealChute, RealHeat, as well as FAR and RSS? Slightly unclear on how far down the dependencies list I should go.

I'll try to get a mod list of what I had in the game at the time I first got this bug, as well. It's worth noting that when I first had the problem, going into the ApolloCSM.cfg file included with Realism Overhaul and changing the position value manually for the heat shield module in the command module part did allow me to manually move the heat shield into the correct place, so at that time I believed it was simply an issue of the value in that config file being incorrect. Seems from what you're all saying that's not the case. Subsequent to me changing some things in that config file, I had a whole slew of other problems with incorrectly-functioning nodes that put all the parts further down the service module stack in the wrong place. For instance, the service module itself was clipping badly into the command module-service module decoupler, without me changing anything about either of those parts directly.

@stratochief66 - As to your question about FASA, that was the very first mod I ever tried to install and I then spent ages with it trying to rectify an unrelated bug it was having which turned out to be associated with the reflections plugin, so I'm not sure I can exactly remember where I first got it from. I *think* I downloaded it from KerbalStuff via a link from the FASA thread on the forums.

**Comment by stratochief66** [comment] 2015-10-18 03:56
@xv323 the ones you've mentioned should be sufficient

There is likely to be some new RSS and RO releases within the next week, so it might be worth waiting until then.

**Comment by RedAV8R** [comment] 2015-10-21 18:04
Being that neither @stratochief66 nor myself can replicate the heat shield having problems should we close this issue?

**Comment by stratochief66** [comment] 2015-10-21 21:26
I'd say so, since we don't have any new data.

**Closed** 2015-10-22 04:58 UTC
