### ISSUE TITLE
RD-270/RD-270m's plume borked, bobcat soviet engine packs

### ISSUE THREAD

**Issue by Temeter** [KSP-RO/RealismOverhaul#406] opened 2015-07-14 05:22 UTC
Both engines got very strange trails, pics:

http://i.imgur.com/RiYyzC7.jpg

**Comment by JandCandO** [comment] 2015-07-14 05:29
I can get to work on these I guess. I did a pass on the BobCat Soviet engines, but I left those 2 alone because they had very nice custom plumes and I didn't want to step on other people's work by changing them. But I guess I can tweak the size and position of the plumes :)

**Comment by Temeter** [comment] 2015-07-14 05:42
Very appreciated! The plumes do look pretty good (fits the weird look of large hypergolic engines's plume), but the trail is rather a bit incoherent at sub/low mach.

Btw, thanks for you awesome work on the soviet engines effects! I'm almost exclusively using them atm.

**Comment by JandCandO** [comment] 2015-07-14 05:46
No problem! Its good to hear props from a contribution to an open source project. Thanks!

**Comment by JandCandO** [comment] 2015-07-14 06:46
Try this out, Temeter. I tweaked some of the plume parameters, but they are still far from perfect. I'm too lazy to put up screenshots though.

https://github.com/KSP-RO/RealismOverhaul/pull/408

**Comment by Temeter** [comment] 2015-07-14 17:47
Hm, the stream is still incoherent. I'm seeing basically these issues:

1. The stream consisting of single clouds is a bit too obvious when watching the rocket. This is mostly the case around ~400m/s, when the stream gets more transparent, as well as the upper part of the giant plume around 1k m/s, where the engine seems to shoot balls.
2. The start of the plume directly on the engine isn't following the rocket nozzles shape, imo one of the most important parts of a good locking rocket effect (and one plume really does tend to do great!). It looks like the plumes are basically spawning around the rocket nozzles, even being bigger than the nozzle itself. This is especially the case below 1k m/s.

Maybe a way to solve these issues would be to add a more distinctive fire effect around the nozzles. 


followed . Similar to this chines hypergolic rocket, around 1:25:
https://www.youtube.com/watch?v=LndYEpfr1UA

I'd say something along of the lines of the nervas plume, just more poisonous reddish than purple, slightly more translucent.

Please mind i've got absolutely no clue how the mod works and how much work that would be, in case i'm suggesting unreasanable things. Or ofc if you don't want to change to much with the original work.
Hm, the stream is still incoherent. I'm seeing basically these issues:

1. The stream consisting of single clouds is a bit too obvious when watching the rocket. This is mostly the case around ~400m/s, when the stream gets more transparent, as well as the upper part of the giant plume around 1k m/s, where the engine seems to shoot balls.
2. The start of the plume directly on the engine isn't following the rocket nozzles shape, imo one of the most important parts of a good locking rocket effect (and one plume really does tend to do great!). It looks like the plumes are basically spawning around the rocket nozzles, even being bigger than the nozzle itself. This is especially the case below 1k m/s.

Maybe a way to solve these issues would be to add a more distinctive fire effect around the nozzles and following plume. Similar to this chinese hypergolic rocket, visible around 1:25. Watch the more translucent, voluminous engine effect below the engines, and the yellowish (?) stream forming in the middle inbetween them:
https://www.youtube.com/watch?v=LndYEpfr1UA
Seems to be something happening to hypergolic engines, here during a short glance at the proton-M (0:27), although I think the chinese style fits more:
https://www.youtube.com/watch?v=NKRT2BRN2HM

I'd say maybe something derrivated of the lines of the nervas plume? Just more poisonous reddish than purple/white, slightly more translucent and larger. Followed by the current green plume, just slightly offsett, strating small and growing.

Please mind i've got absolutely no clue how the mod works and how much work that would be, in case i'm suggesting unreasanable things. Or ofc if you don't want to change to much with the original work. In that case leaving it like this might be the correct option.

**Comment by JandCandO** [comment] 2015-07-14 18:55
Normally, this would be relatively easy because Felger has gone ahead and made an array of pre-fabricated plumes that are generic to the different fuel types and can be applied to almost any engine. That method is pretty easy to use since it only puts you in control of a few variables, and the prefabbed plume config handles the rest. Unfortunately, nobody has gotten around to making a prefabbed plume for the fuel mixtures that these engines use.

Making plumes from scratch is a pretty involved, I would have to tweak the plume expansion curves and all these other variables. It isn't impossible, but I'm not confident that I can do a good enough job with that method. I can try, but I'll need some time.

**Comment by JandCandO** [comment] 2015-07-14 18:56
Also, thanks for the videos. They'll help my attempt a lot.

**Comment by JandCandO** [comment] 2015-07-14 18:57
@Temeter , when you try to download RO in its current development state, are you downloading from the releases page or the repository page? Go to the repository page and click the "download zip" button.

**Comment by Temeter** [comment] 2015-07-14 20:15
Yeah, now it's downloaded and installed correctly (SLS engine looks SciFi again :D ). Either wasn't udated yet or I confused zips. Nvm me.^^'

I was afraid something like this would bet the case, since there aren't any large hypergolic lower stage engines in normal RO. The small RD-855 UDMH/NTO driven verniers might be worth a look, but those are ofc very small engines, while the RD-270 are some of the largest engine concepts.

**Comment by JandCandO** [comment] 2015-07-14 20:40
I'm going to leave this to someone who knows what they are doing... I just discovered I don't really have time to try getting this done.

**Comment by Felger** [comment] 2015-07-14 20:40
@JandCandO / @Temeter, can you submit an issue to [the RealPlume repo](https://github.com/KSP-RO/RealPlume/issues) with the fuel combinations you'd like to see (bonus prize if you include reference video!) and I'll see what I can do.  Still need to tweak the expansion and vacuum appearance on a few of our plumes, but it'll go on my list!

**Comment by Temeter** [comment] 2015-07-14 20:48
Don't sweat it JandCando, sounds like a lot of hard work. 

I'll drop issues, Felger! Thanks, there are lots of powerful UDMH engines, from Ariane 4, Long March over Proton, etc.

**Comment by Felger** [comment] 2015-07-14 20:56
It's kind of the wrong color, it's a good color for the Titan, but the Proton is a little more yellow.  It'd work as a decent stand-in until I can build a better one though.

In fact, that sounds like an excellent idea.  It'll be quicker for me if you get some reference videos together (bonus points for altitude annotation on the video) so i can put the plume together.

**Comment by Temeter** [comment] 2015-07-14 21:01
Ok, I'll take a look, check some material (doesn't seem to exist much, sadly) of hypergolic rocket engines.

**Comment by Temeter** [comment] 2015-07-15 01:21
I've check lots and lots of videos and pics, and more confused than before. I honestly can't really differentiate the rockets plumes. Proton M and the Chinese Long March rockets should deliver good impressions since they are UDMH/NTO only. This rocket does look kind of reddish (video is a crash, but it shows a lot of the plumes):
https://www.youtube.com/watch?v=vqW0LEcTAYg
Then I changed the config for the stock F1 engine to get a nice look at the effect, and the result is this, which looks pretty similar in concept to me, maybe even a bit more yellow:
http://i.imgur.com/VvbXPbf.jpg

Maybe I'm looking for the wrong things, but know I'm just confused as to what to look for.

**Comment by Felger** [comment] 2015-07-15 01:28
The coloration is about as close as we're going to get it without coming up with our own custom particle (Ferram already built one for us) I think the Hypergolic-Lower|Upper should probably work well based on your reference material.

**Comment by Temeter** [comment] 2015-07-15 02:19
Sorry, I think I'm misunderstanding you. It's 4 o'clock over here and english isn't my first language, I can almost feel my brain slowing down.^^'
Please help me out:

When you said 'It'd work as a decent stand-in until I can build a better one though.', what were you talking about?
1. About making another one specifically more fitting the color scheme of the russian style UDMH engine (meaning proton + RD270)?

2. Or was it actually about replacing it by a completely new and better looking effect for hypergolic engines in general, and that's what you asked me to make an issue+material for?

Or was you last post basically just saying that 1. was your idea, but my material showed that using the current hypergolic prefab effect is just fine?

**Comment by Felger** [comment] 2015-07-15 02:22
I'm thinking the last one, based on your material the current plume effect is pretty good.  If you have any suggestions to make it better, submit an issue and I'll see what I can do!

**Comment by Temeter** [comment] 2015-07-15 02:30
Ahso, thanks for the patience! I'd also found it to be quite good. The real rocket effect is very simple and the game does reflect that quite well.

Can't really think of any way to improve the effect. At least not with some form of distortion, post procession, illumination and generally another graphics engine. ;)

**Comment by Temeter** [comment] 2015-07-17 20:18
Sorry, completely forgot this thing was still open. Since the conclusion is that we actually have a good prefab, can someone make the update to point the RD270/270m to the 'Hypergolic-Lower.cfg'?

I've, sadly, got no clue how to do this.

**Comment by JandCandO** [comment] 2015-07-17 20:42
That I can do, Temeter. So we're just going to set the plumes of both the RD-270 and RD-270M to Hypergolic-Lower?

**Comment by Temeter** [comment] 2015-07-17 21:12
Jep! I've compared the real effects of UDMH engines from the protom starts and checked the hypergolic lower in large on an F1 engines, and, while generally just good looking, it's really close to reality. I'd say that's enough to justify the change.

**Comment by JandCandO** [comment] 2015-07-17 22:15
For the Hypergolic-Lower effect, it would be much better if there wasn't any offset curve for the plume. I haven't been able to make it go away in the config, though. I have tried the following with no success:

```
@PART[RD270]:FOR[zzRealPlume]:AFTER[zRealPlume] //Adjusting plume
{
  @EFFECTS
  {
    @Hypergolic-Lower
    {
      @MODEL_MULTI_PARTICLE_PERSIST[plume]
      {
        !offset
      }
    }
  }
}
```

```
@offset{}
```

```
@offset
{
     @density = 1.0 0
     @density = 0.2 0
     @density = 0.1 0
     @density = 0.05 0
     @density = 0.0 0
}
```
```
@offset
{
     density = 1.0 0
     density = 0.2 0
     density = 0.1 0
     density = 0.05 0
     density = 0.0 0
}
```

So what is the right way to do this? I'm not too familiar with how to use MM in this context.

**Comment by Felger** [comment] 2015-07-18 03:11
I've actually fixed this for the next release, and I plan on pushing that in the next day or two.  Honestly, I really just need to stop using Offset, it just gets me in trouble.

However, the proper way to get rid of offset in this case is like so:

```
!offset{}
```
If you wanted to adjust the offset, you could do it like so:
```
@offset
{
   @density,0 = 1.0 0
   @density,1 = 0.2 0
   @density,2 = 0.0 0
}

**Comment by JandCandO** [comment] 2015-07-18 12:19
Ohhh, I need to include a key for that kind of thing. Ok that clears things up for me. Thanks!

**Comment by JandCandO** [comment] 2015-07-18 14:46
I just can't seem to get my config to work as intended, I could use some help. Here is my current config:

```
@PART[RD270]:FOR[RealPlume]:NEEDS[SmokeScreen] //RD-270
{
    PLUME
    {
        name = Hypergolic-Lower
        transformName = thrustTransform
        localRotation = 0,0,0
        localPosition = 0,0,3
        fixedScale = 4
        energy = 2
        speed = 1
    }
    @MODULE[ModuleEngines*]
    {
        @name = ModuleEnginesRF
    }
    @MODULE[ModuleEngineConfigs]
    {
        %type = ModuleEnginesRF
        @CONFIG,*
        {
            %powerEffectName = Hypergolic-Lower
        }
    }
}

@PART[RD270]:FOR[zzRealPlume]:AFTER[zRealPlume] //Moving flare deeper into bell
{
  @EFFECTS
  {
    @Hypergolic-Lower
    {
      @MODEL_MULTI_PARTICLE_PERSIST[flare]
      {
        @localPosition = 0,0,1.5
        @fixedScale = 3
      }

      @MODEL_MULTI_PARTICLE_PERSIST[plume]
      {
        @offset
        {
            @density,0 = 1.0 0
            @density,1 = 0.2 0
            @density,2 = 0.1 0
            @density,3 = 0.05 0
            @density,4 = 0.0 0
        }
      }
    }
  }
}
```

The basic plume is working as intended, but the offsets aren't being set to 0 and the flare position isn't being changed. I also tried !offset{}, but that didn't work either.

**Comment by Felger** [comment] 2015-07-18 15:00
No, but you're taking the long way around on the config, try this instead:

```
@PART[RD270]:FOR[RealPlume]:NEEDS[SmokeScreen] //RD-270
{
    PLUME
    {
        name = Hypergolic-Lower
        transformName = thrustTransform
        localRotation = 0,0,0
        plumePosition = 0,0,3
        flarePosition = 0,0,4
        fixedScale = 4
        energy = 2
        speed = 1
    }
    @MODULE[ModuleEngines*]
    {
        @name = ModuleEnginesRF
    }
    @MODULE[ModuleEngineConfigs]
    {
        %type = ModuleEnginesRF
        @CONFIG,*
        {
            %powerEffectName = Hypergolic-Lower
        }
    }
}

@PART[RD270]:FOR[zzRealPlume]:AFTER[zRealPlume] //Moving flare deeper into bell
{
  @EFFECTS
  {
    @Hypergolic-Lower
    {
      @MODEL_MULTI_PARTICLE_PERSIST[flare]
      {
        @fixedScale = 3
      }
    }
  }
}
```

As I said, the offset is being fixed in today's release, so don't bother removing it in your config.  It should never have been there in the first place.  Also, the flare/plume for Hypergolics should be sized appropriately to each other, can I see a screenshot of what you're trying to do by setting the flare to 75%?

As a general rule, I do need to re-order the flare/plume so the plume draws in front of the flare, but the sizing should be good.

**Comment by JandCandO** [comment] 2015-07-18 15:37
Here's an Imgur album that describes what I'm trying to do here: http://imgur.com/a/OjcMS

Also, I used the config you posted above with the latest version of RealPlume, and the flare didn't change position or scale...

**Comment by Felger** [comment] 2015-07-18 15:43
Oops, that second node should be FOR[zzRealPlume], not AFTER[zRealPlume].  AFTER zRealPlume is where the actual engine effects get attached.

And if you have RealPlume v0.3, flarePosition|plumePosition should work just fine.

**Comment by JandCandO** [comment] 2015-07-18 16:04
Ok, that seemed to fix all the remaining problems. I'll get to work on the commit now.

**Comment by JandCandO** [comment] 2015-07-18 16:14
Alright, https://github.com/KSP-RO/RealismOverhaul/pull/421 fixes this issue. The plume for both engines are exactly the same.

**Comment by Temeter** [comment] 2015-07-18 16:37
Wonderfull. Thanks for your work, ladies and/or gentleman, i'm closing this thing.

**Closed** 2015-07-18 16:57 UTC
