### ISSUE TITLE
Weird attachment nodes on FASAApollo_SM_Engine?

### ISSUE THREAD

**Issue by aw94** [KSP-RO/RealismOverhaul#239] opened 2015-04-16 21:21 UTC
The two-node setup on the thrust structure seemed kind of strange to me, so checking to see if this is the intended setup. @stratochief66 

![screen shot 2015-04-16 at 4 54 34 pm](https://cloud.githubusercontent.com/assets/566572/7191603/e5cb58d8-e45c-11e4-884c-eebe0f6fa6cb.png)

**Comment by stratochief66** [comment] 2015-04-17 12:48
This is as intended, to solve the problem of giving the LMA a node to attach to on the top end. This could also be solved with a similar extra node in the SM fuel tank, which I originally thought of as a better solution.

However, I heard a people saying this was they way the problem was solved before things got borked and I was fixing them. The advantage of having the node with the engine is you can still use the SM engine with a custom shorter SM fuel tank, such as with later Apollo blocks intended for LEO or other activity.

**Comment by aw94** [comment] 2015-04-17 14:49
Ah, ok. Guess I'll close this then, since it actually isn't an issue. Thanks!

**Comment by NathanKell** [comment] 2015-04-17 17:17
Why not position the node on the SLA such that the bottom node of the SPS can be used? I'm not seeing the need for the third node.

**Comment by stratochief66** [comment] 2015-04-17 17:26
Hmm. That is likely to work. I don't recall if there was a reason I didn't do that. I will try that out shortly and see how well it works.

**Comment by NathanKell** [comment] 2015-04-24 21:43
Closed by #240.

**Closed by NathanKell** 2015-04-24 21:43 UTC
