### ISSUE TITLE
Engine Config Tech Transfer String Formatting

### ISSUE THREAD

**Issue by ryanc55** [KSP-RO/RealismOverhaul#2484] opened 2021-07-11 21:15 UTC
Some engines seem to have a typo in the techtransfer string.  E.g. RD-107 and RD-108.   This is causing tech to not transfer or accumulate for the affected configs.  It also causes bugs in the VAB when you try to attach a configured engine.   The engine fails to attach but still shows as linked on the parent part, which corrupts the craft file.

I believe this is due to a comma instead of an ampersand in between differing transfer percentages.  e.g.

techTransfer = RD-200:25,RD-107-8D74PS,RD-107-8D74:50

Should be:

techTransfer = RD-200:25&RD-107-8D74PS,RD-107-8D74:50

At least that fixed it in my install.

**Comment by jwvanderbeck** [comment] 2021-07-11 21:17
https://github.com/KSP-RO/RealismOverhaul/issues/2481

**Comment by NathanKell** [comment] 2021-07-11 21:18
Dupe of https://github.com/KSP-RO/RealismOverhaul/issues/2481 but we really do need to sort it out! Thanks!

**Closed by NathanKell** 2021-07-11 21:18 UTC
